// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Baz interface {
	IsBaz()
}

type Bar struct {
	Bar string `json:"bar"`
}

func (Bar) IsBaz() {}

type Data struct {
	Baz Baz `json:"baz"`
}

type Foo struct {
	Foo string `json:"foo"`
}

func (Foo) IsBaz() {}
